name: stream 
version: 0.0.0
homepage: https://github.com/morloclib/stream
synopsis: Core functions for stream processing
description: A stub for stream processing
category: basic
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: https://github.com/morloclib/stream
bug-reports: https://github.com/morloclib/stream
cpp-version: 17
